### ISSUE TITLE
Open Source Legend Engine code

### ISSUE THREAD

**Issue by aitana16** [finos/legend#146] opened 2020-06-09 00:39 UTC
Depends on
-[  ] [Phase 2: M2.1b – Execution Code Uplift](https://github.com/finos/alloy/milestone/10)
-[  ] [Test build and deploy works in open source environment for Engine](https://github.com/finos/alloy/issues/133)

**Comment by brooklynrob** [comment] 2020-07-16 14:37
Depends on
[ ] [Phase 2: M2.1b – Execution Code Uplift](https://github.com/finos/alloy/milestone/10)
[ ] [Test build and deploy works in open source environment for Engine](https://github.com/finos/alloy/issues/133)

**Comment by brooklynrob** [comment] 2020-10-19 02:13
Completed when github repo is switched from private to public

**Comment by brooklynrob** [comment] 2020-10-19 02:14
Dupe of https://github.com/finos/alloy/issues/233?

**Comment by maoo** [comment] 2020-10-19 09:43
https://github.com/finos/legend-engine

**Closed by maoo** 2020-10-19 09:43 UTC
Labels: Alloy Engagements, Alloy Engine, Code_Readiness, Launch (Eve and Day of) Wave 1 Checklist, Wave 1 Go Live Readiness Checklist
